### ISSUE TITLE
DMAX changed embedding of Video Player - no showid used

### ISSUE THREAD

**Issue by hrueppert** [Brawl345/Get-DMAX-Links#9]
First of all, thanks for your great work.

I just tried to retrieve the video content of this link: 
https://dmax.de/sendungen/die-modellbauer-das-miniatur-wunderland/abgerissen/

In the source code is no show id anymore. 

`<hyoga-player uid="562c9437372439bd" playerselector="hyogaPlayer-562c9437372439bd" videolibrary="videojs" sourcetype="sonic" locale="de" playertype="videoPlayer" assetid="178008" playbacktype="video" autoplay="false" muted="false" id="hyogaManager-562c9437372439bd" endpoint="https://eu1-prod.disco-api.com" realm="dmaxde">`

i guess the now use assetid to identify the shows. maybe it's possible to extend the code to use both.

**Comment by Brawl345** [comment]
Hm, this is a page for a single episode, but the main page also has no showId (because it has no embedded player for all episodes, like Steel Buddies f.e.). 

Let's see...

The URL for this is
```
https://eu1-prod.disco-api.com/content/videos/178008?include=primaryChannel,primaryChannel.images,show,show.images,genres,tags,images,contentPackages&sort=name&page[number]=1&page[size]=100
```
where `178008` is the assetId. Under data -> relationships -> show -> data ->id is the showId we need (16326 for yours)!

![showid](https://user-images.githubusercontent.com/5049892/100117998-b1902f80-2e75-11eb-9ac2-c3c58587bd8e.png)

Shouldn't be too hard to implement, but will probably be an extra parameter

**Comment by Brawl345** [comment]
Just pass `-isasset` to the script!
